#!/bin/bash

# Ensure the OpenAI API key is set
if [ -z "$OPENAI_API_KEY" ]; then
  	echo "Error: Please set your OpenAI API key in the OPENAI_API_KEY environment variable."
  	exit 1
fi

if [ -z "$OPENAI_THREAD_ID" ]; then
	echo "Error: Set OPENAI_THREAD_ID to DELETE."
	exit 1
fi

# Make a request to create a new thread
response=$(curl -s -H "Authorization: Bearer $OPENAI_API_KEY" \
                 -H "Content-Type: application/json" \
		 -H "OpenAI-Beta: assistants=v2" \
                 -d '' \
		 -X DELETE \
                 "https://api.openai.com/v1/threads/$OPENAI_THREAD_ID")

# Extract and display the thread ID
deleted=$(echo $response | jq -r '.deleted')
echo "$deleted"
